config/routes.rb
Rails.application.routes.draw do

  resources :events
  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/clear'
  get 'sessions/debug', :to => 'sessions#debug', :via => [:get, :post]
    
  resources :users, only: [:destroy] do
    resources :profiles, only: [:show, :edit, :update, :destroy]
  end    

  get 'about' => 'landing_page#about'
  get 'landing_page/index'
  root 'landing_page#index'
    

end

app/models/event.rb
require 'json'
require 'httparty'
require 'twitter'

class Event < ActiveRecord::Base    
    def self.search_description(query, sort_key)
        if not @sort_key
            @sort_key = 'description'
        end
        Event.where("description LIKE ?", "%#{query}%").order(sort_key)
    end

    def self.create info
        create!(description: info['description'])
    end
    
    def self.create_from_twitter
        @eventslist = []
        #@event = Event.new(event_params)
         Event.all.each do |e|
             Event.delete(e)
         end

        client = Twitter::REST::Client.new do |config|
          config.consumer_key        = ENV["TWITTER_CLIENT_ID"] 
          config.consumer_secret     = ENV["TWITTER_CLIENT_SECRET"]
        end

        @Tweets = client.user_timeline('binghamtonu', count: 3200)
        #Tweets.each { |tweet| puts tweet.full_text }

        @Tweets.each do  |tweet|
          if tweet.full_text =~ /(a\.m\.|p\.m\.)/
            @eventslist.push(Event.new({:description => tweet.full_text,:date => tweet.created_at})) 
            p tweet.full_text
          end
        end 

        @eventslist.each do |x|
          x.save
        end

        return @eventslist
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  skip_before_action :keep_out_unless_logged_in
  before_action :set_event, only: [:show]#, :edit, :update, :destroy]

  # GET /events
  def index
    update_events_hash
    render_or_redirect
    @sort_key = sort_key
    @query_key = query_key
    @events = Event.search_description(@query_key, @sort_key)
  end

  # GET /events/1
  def show
    @event = Event.find(params[:id])
  end

  # GET /events/new
#  def new
#    @event = Event.new
#  end

  # GET /events/1/edit
#  def edit
#  end

  # POST /events
  def create
     @eventslist = Event.create_from_twitter
      
    redirect_to events_url
    
  end

  # PATCH/PUT /events/1
#  def update
#    if @event.update(event_params)
#      redirect_to @event, notice: 'Event was successfully updated.'
#    else
#      render :edit
#    end
#  end

  # DELETE /events/1
#  def destroy
#    @event.destroy
#    redirect_to events_url, notice: 'Event was successfully destroyed.'
#  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def event_params
      params[:event]
    end
    
    def sort_key
      session[:sort]
    end
    
    def query_key
      session[:query]
    end
    
    def update_events_hash
      session[:sort] = params[:sort] || session[:sort] || :id
      session[:query] = params[:query] || session[:query]
    end
    
    def render_or_redirect
      return unless (session[:sort] and params[:sort].nil? or session[:query] and params[:query].nil?)
      redirect_to events_path(:sort => session[:sort], :query => session[:query])
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message

  .actions
    = f.submit 'Save'

app/views/events/edit.html.haml
%h1 Editing event

= render 'form'

= link_to 'Show', @event
\|
= link_to 'Back', events_path

app/views/events/index.html.haml
%h1 Listing events
%p1 
  = "Sort By: "
  = link_to "Date", events_path(:sort => :date)
  = link_to "Description", events_path(:sort => :description)
  %form{ :action => events_path, :method => "get" }
    %input{:placeholder => @query_key, :required => "", :type => "text", :name => "query"}
      %button{:type => "submit"} Search
  = link_to "Clear", events_path(:sort => "", :query => "")
%table
  %thead
    %tr
      %th
      %th
      %th

  
  - @events.each_slice(4).to_a.each do |events_split|
    %div{class: "card-group"}
      - events_split.each do |event|
        %div{class: "card", style: "max-width: 18rem;"}
          %div{class: "card-body"}
            %h5{class: "card-title"}
              = event.description
              
            %h6{class: "card-subtitle mb-2 text-muted"}
              = event.date
            %a{href: event_path(event.id), class: "card-link"}
              View event
    %br
    //      %tr
    //       %td= link_to 'Show', event
    //        %td= link_to 'Edit', edit_event_path(event)
    //        %td= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' }

%br

//= button_to 'New Event', @events.create, class: "btn btn-primary"

app/views/events/new.html.haml
%h1 New event

= render 'form'

= link_to 'Back', events_path

app/views/events/show.html.haml
%h1 Event Details

%div{class: "card", style: "max-width: 100rem;"}
  %div{class: "card-body"}
    //%h3{class: "card-title"}
    //  = event.title
    //%h5{class: "card-subtitle"}
    //  = event.date
    %p{class: "card-text"}
      = @event.description
      
=link_to "Back To Events", events_path