config/routes.rb
Rails.application.routes.draw do

  resources :events
  match '/auth/:provider/callback', :to => 'sessions#create', :via => [:get, :post]
  match 'auth/failure', :to => 'sessions#failure', :via => [:get, :post]
  match 'sessions/destroy', :as => 'logout', :via => [:get, :post]
  get 'sessions/clear'
  get 'sessions/debug', :to => 'sessions#debug', :via => [:get, :post]
    
  resources :users, only: [:destroy] do
    resources :profiles, only: [:show, :edit, :update, :destroy]
  end    

  get 'about' => 'landing_page#about'
  get 'landing_page/index'
  root 'landing_page#index'
    

end

app/views/layouts/_flash.html.haml
- if flash[:notice]
  #notice.alert.alert-info{role: "alert"}
    = flash[:notice]
- elsif flash[:warning]
  #warning.alert.alert-danger{role: "alert"}
    = flash[:warning]

app/views/layouts/_footer.html.haml
%div
= button_to "Log Out", logout_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BU Event Board
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %div{:class => "container"}
      %h1
        =link_to "BU Event Board", root_path
        = render "layouts/flash"
      = yield
    %footer{:class => "footer mt-auto py-3 bg-light"}
      %div{:class => "container"}
        %p{:class => "footer-text"}
          =link_to "Home", root_path
          |
          =link_to "About", about_path
          - unless @action == 'login'
            = render "layouts/footer"